# Generated by Django 3.0.2 on 2020-01-25 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=50)),
                ('hospitaladdress', models.CharField(max_length=50)),
                ('hospitalemail', models.EmailField(max_length=25)),
                ('hospitalpassword', models.CharField(max_length=10)),
                ('hospitalnumber', models.IntegerField()),
                ('hospitalpan', models.IntegerField()),
                ('login_date', models.DateField(default=datetime.date.today)),
                ('hospitalprofile', models.ImageField(upload_to='hospitalimage')),
            ],
        ),
        migrations.CreateModel(
            name='hospitalactivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('postid', models.IntegerField()),
                ('useractivity', models.CharField(default='blank', max_length=1000)),
                ('meme', models.ImageField(default='blank', upload_to='meme')),
                ('uploaddate', models.DateField(default=datetime.date.today)),
                ('hospitalprofile', models.ImageField(upload_to='hospitalimage')),
            ],
        ),
    ]
